#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /
    controller: App\Controller\PagesController::login
    defaults:
        template: 'login.html.twig'

login_action:
    path: login_action
    controller: App\Controller\PagesController::login_action
    defaults:
        template: 'login.html.twig'

logout_action:
    path: logout
    controller: App\Controller\PagesController::logout_action
    defaults:
        template: 'login.html.twig'

employees:
    path: employees
    controller: App\Controller\PagesController::employees
    defaults:
        template: 'employees.html.twig'

add_employee_action:
    path: add_employee_action
    controller: App\Controller\PagesController::add_employee_action
    defaults:
        template: 'employees.html.twig'

delete_employee_action:
    path: delete_employee_action/{id}
    controller: App\Controller\PagesController::delete_employee_action
    defaults:
        template: 'employees.html.twig'