#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /
    controller: App\Controller\PagesController::login
    defaults:
        template: 'login.html.twig'

login_action:
    path: login_action
    controller: App\Controller\PagesController::login_action
    defaults:
        template: 'login.html.twig'

logout_action:
    path: logout
    controller: App\Controller\PagesController::logout_action
    defaults:
        template: 'login.html.twig'

employees:
    path: employees
    controller: App\Controller\PagesController::employees
    defaults:
        template: 'employees.html.twig'

add_employee_action:
    path: add_employee_action
    controller: App\Controller\PagesController::add_employee_action
    defaults:
        template: 'employees.html.twig'

delete_employee_action:
    path: delete_employee_action/{id}
    controller: App\Controller\PagesController::delete_employee_action
    defaults:
        template: 'employees.html.twig'

edit_employee_action:
    path: edit_employee_action/{id}
    controller: App\Controller\PagesController::edit_employee_action
    defaults:
        template: 'employees.html.twig'

schedule:
    path: schedule
    controller: App\Controller\PagesController::schedule
    defaults:
        template: 'schedule.html.twig'

my_schedule:
    path: my_schedule
    controller: App\Controller\PagesController::my_schedule
    defaults:
        template: 'my_schedule.html.twig'

add_appointment_action:
    path: add_appointment_action
    controller: App\Controller\PagesController::add_appointment_action
    defaults:
        template: 'my_schedule.html.twig'

edit_appointment_action:
    path: edit_appointment_action/{id}
    controller: App\Controller\PagesController::edit_appointment_action
    defaults:
        template: 'my_schedule.html.twig'

delete_appointment_action:
    path: delete_appointment_action/{id}
    controller: App\Controller\PagesController::delete_appointment_action
    defaults:
        template: 'my_schedule.html.twig'

get_schedule_day:
    path: get_schedule_day
    controller: App\Controller\PagesController::get_schedule_day
    defaults:
        template: 'my_schedule.html.twig'

        